/**
 * TaskEngine.js
 * =============
 * Converts rules outputs (derived deadlines + alerts) into reproducible auto tasks
 * while preserving manual tasks.
 */

import { TASK_PRIORITY, TASK_STATUS } from '../core/Constants.js';
import { getTodayLegalDate, normalizeLegalDateInput } from '../utils/DateUtils.js';

function normalizeDate(value) {
  if (!value) return '';
  const legalDate = normalizeLegalDateInput(value);
  if (legalDate) return legalDate;
  return '';
}

function makeTaskId(seed) {
  return `task:${String(seed || '').replace(/[^a-zA-Z0-9_-]/g, '_')}`;
}

function priorityFromRisk(riskLevel) {
  if (riskLevel === 'critical') return TASK_PRIORITY.CRITICAL;
  if (riskLevel === 'high') return TASK_PRIORITY.HIGH;
  return TASK_PRIORITY.MEDIUM;
}

function priorityFromSeverity(severity) {
  if (severity === 'critical') return TASK_PRIORITY.CRITICAL;
  if (severity === 'warning') return TASK_PRIORITY.HIGH;
  return TASK_PRIORITY.MEDIUM;
}

export function createAutoTaskPayload(task = {}, defaults = {}) {
  const payload = { ...(task || {}) };
  const fallbackPriority = defaults.priority || TASK_PRIORITY.MEDIUM;
  const fallbackStatus = defaults.status || TASK_STATUS.OPEN;
  payload.priority = payload.priority || fallbackPriority;
  payload.status = payload.status || fallbackStatus;
  if (payload.autoGenerated === undefined) payload.autoGenerated = true;
  return payload;
}

export class TaskEngine {
  constructor(settings = {}) {
    this.settings = {
      enabled: true,
      createAlertTasks: true,
      createDeadlineTasks: true,
      ...settings
    };
  }

  /**
   * Convert rule evaluation output to auto tasks.
   * @param {object} caseData
   * @param {object} evaluation - output from RulesEngine.evaluateCase
   * @param {Array} existingTasks
   * @returns {{ tasks: Array, meta: object }}
   */
  generateFromRules(caseData, evaluation, existingTasks = []) {
    if (!this.settings.enabled || !evaluation) {
      return { tasks: existingTasks || [], meta: { skipped: true } };
    }

    const generated = [];

    if (this.settings.createDeadlineTasks) {
      for (const deadline of evaluation.deadlines || []) {
        if (deadline.status !== 'active') continue;
        const task = this.buildTaskFromDeadline(caseData, deadline);
        if (task) generated.push(task);
      }
    }

    if (this.settings.createAlertTasks) {
      for (const alert of evaluation.alerts || []) {
        if (alert.dismissed) continue;
        if (alert.severity === 'info') continue;
        const task = this.buildTaskFromAlert(caseData, alert);
        if (task) generated.push(task);
      }
    }

    // Include direct tasks generated by rules catalog.
    for (const task of evaluation.tasks || []) {
      const normalizedTask = this.normalizeRuleTask(caseData, task);
      if (normalizedTask) generated.push(normalizedTask);
    }

    const merged = this.mergeAutoTasks(existingTasks, generated);

    return {
      tasks: merged,
      meta: {
        generatedCount: generated.length,
        finalCount: merged.length
      }
    };
  }

  buildTaskFromDeadline(caseData, deadline) {
    const dueDate = normalizeDate(deadline.dueDate);
    if (!dueDate) return null;

    return createAutoTaskPayload({
      id: makeTaskId(`deadline-${caseData.id}-${deadline.id}`),
      workspaceId: caseData.workspaceId,
      caseId: caseData.id,
      entityType: 'case',
      entityId: caseData.id,
      title: `متابعة: ${deadline.label}`,
      description: deadline.reasonText || 'مهمة مولدة تلقائيًا من ميعاد قانوني.',
      dueDate,
      priority: priorityFromRisk(deadline.riskLevel),
      status: TASK_STATUS.OPEN,
      source: 'rule',
      originSource: 'rule',
      originRuleId: deadline.sourceRuleId || '',
      generatedFrom: {
        type: 'deadline',
        id: deadline.id
      },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    });
  }

  buildTaskFromAlert(caseData, alert) {
    const dueDate = normalizeDate(alert.dueDate || getTodayLegalDate());
    if (!dueDate) return null;

    return createAutoTaskPayload({
      id: makeTaskId(`alert-${caseData.id}-${alert.id}`),
      workspaceId: caseData.workspaceId,
      caseId: caseData.id,
      entityType: 'case',
      entityId: caseData.id,
      title: `تنبيه إجرائي: ${alert.title}`,
      description: alert.message || 'مهمة مولدة تلقائيًا من تنبيه إجرائي.',
      dueDate,
      priority: priorityFromSeverity(alert.severity),
      status: TASK_STATUS.OPEN,
      source: 'rule',
      originSource: 'rule',
      originRuleId: alert.sourceRuleId || '',
      generatedFrom: {
        type: 'alert',
        id: alert.id
      },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    });
  }

  normalizeRuleTask(caseData, task) {
    const dueDate = normalizeDate(task.dueDate || getTodayLegalDate());
    if (!dueDate) return null;

    return createAutoTaskPayload({
      id: task.id || makeTaskId(`rule-${caseData.id}-${task.sourceRuleId || 'task'}`),
      workspaceId: caseData.workspaceId,
      caseId: caseData.id,
      entityType: 'case',
      entityId: caseData.id,
      title: task.title || 'مهمة آلية',
      description: task.description || '',
      dueDate,
      priority: task.priority || TASK_PRIORITY.MEDIUM,
      status: task.status || TASK_STATUS.OPEN,
      taskType: task.taskType || 'auto',
      source: 'rule',
      originSource: 'rule',
      originRuleId: task.sourceRuleId || task.originRuleId || '',
      generatedFrom: task.generatedFrom || { type: 'rule_task', id: task.id || '' },
      createdAt: task.createdAt || new Date().toISOString(),
      updatedAt: new Date().toISOString()
    });
  }

  /**
   * Merge rule-generated tasks with existing tasks.
   * Manual tasks are preserved as-is.
   */
  mergeAutoTasks(existingTasks = [], generatedAutoTasks = []) {
    const manualTasks = (existingTasks || []).filter((task) => {
      const source = String(task.originSource || task.source || 'manual');
      return source !== 'rule';
    });

    const stableGenerated = [];
    const seen = new Set();

    for (const task of generatedAutoTasks) {
      if (!task) continue;
      const fingerprint = `${task.title}|${task.dueDate}|${task.originRuleId}|${task.caseId}`;
      if (seen.has(fingerprint)) continue;
      seen.add(fingerprint);
      stableGenerated.push(task);
    }

    return [...manualTasks, ...stableGenerated];
  }
}

export default TaskEngine;
