import { useEffect, useMemo, useState } from 'react';
import { useWorkspace } from '@/contexts/WorkspaceContext';
import { useCases } from '@/contexts/CaseContext';
import storage from '@/data/Storage.js';
import { openCasePanel } from '@/utils/openCasePanel.js';
import { useDisplaySettings } from '@/hooks/useDisplaySettings.js';
import { formatCaseNumber } from '@/utils/caseUtils.js';
import { confirmDialog } from '@/utils/browserFeedback.js';

// ────────────────────────────────────────────────────────────
// TASK CLASSIFICATION & PRIORITY MATRIX
// ────────────────────────────────────────────────────────────

const TABS = [
  { id: 'manual', label: '📋 قائمة المهام', desc: 'المهام اليدوية' },
  { id: 'procedural', label: '⚡ إجراءات القضايا', desc: 'إجراءات الجلسات' },
  { id: 'auto', label: '⚙️ تلقائية', desc: 'طلبات الإطلاع والمواعيد' },
  { id: 'all', label: 'الكل', desc: '' },
];

function classifyTask(task, cases, urgentDays = 10) {
  const today = new Date().toISOString().split('T')[0];
  const daysLeft = task.dueDate
    ? Math.ceil((new Date(task.dueDate) - new Date()) / 86400000)
    : null;

  // Get related case
  const relatedCase = cases.find((c) => String(c?.id || '') === String(task.caseId || ''));

  const isUrgent =
    (daysLeft !== null && daysLeft >= 0 && daysLeft <= urgentDays) ||
    (task.autoGenerated && task.priority === 'critical');

  const isImportant =
    task.priority === 'critical' ||
    task.priority === 'high' ||
    relatedCase?.flags?.isImportant ||
    relatedCase?.flags?.isPlaintiff;

  const isOverdue = daysLeft !== null && daysLeft < 0 && task.status !== 'done';

  return { isUrgent, isImportant, isOverdue, daysLeft, relatedCase };
}

function getTaskType(task) {
  if (task?.taskType) return task.taskType;
  if (task.autoGenerated === true) return 'auto';
  if (String(task.source || '') === 'procedural') return 'procedural';
  return 'manual';
}

function getTaskRuleMeta(task) {
  const ruleId = String(
    task?.createdByRuleId
    || task?.originRuleId
    || task?.sourceRuleId
    || ''
  ).trim() || null;

  const explanation = String(task?.explanation || '').trim();
  const ruleDisplayName = String(
    task?.createdByRuleName
    || task?.ruleDisplayName
    || ''
  ).trim() || (explanation || null);

  const isAuto = (
    task?.autoGenerated === true
    || getTaskType(task) === 'auto'
    || String(task?.source || '').trim() === 'rule'
  );

  return { isAuto, ruleId, ruleDisplayName };
}

function isInspectionTask(task) {
  const title = String(task?.title || '');
  return title.startsWith('طلب إطلاع:') || task?.source === 'inspection';
}

function formatDate(value) {
  if (!value) return '—';
  return String(value).split('-').reverse().join('/');
}

// ────────────────────────────────────────────────────────────
// PRIORITY COLORS & STYLING
// ────────────────────────────────────────────────────────────

const PRIORITY_COLORS = {
  critical: '#dc2626',
  high: '#ea580c',
  medium: '#d97706',
  low: '#2563eb',
};

const PRIORITY_BG = {
  critical: '#fee2e2',
  high: '#ffedd5',
  medium: '#fef3c7',
  low: '#dbeafe',
};

export default function Tasks() {
  const { currentWorkspace } = useWorkspace();
  const { cases } = useCases();
  const displaySettings = useDisplaySettings();

  const [tasks, setTasks] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  // Tabs: manual, procedural, auto, all
  const [activeTab, setActiveTab] = useState('manual');
  const [showAddForm, setShowAddForm] = useState(false);

  // Urgency threshold (configurable)
  const [urgentDays, setUrgentDays] = useState(() => {
    const stored = localStorage.getItem('lb_urgent_days');
    return stored ? Number(stored) : 10;
  });

  const [newTask, setNewTask] = useState({
    title: '',
    caseId: '',
    priority: 'high',
    dueDate: '',
    notes: '',
    reminderBefore: 0,
    taskType: 'manual',
    assignedTo: '',
  });

  const [searchQuery, setSearchQuery] = useState('');
  const [activePriority, setActivePriority] = useState('all');
  const [editingTask, setEditingTask] = useState(null);

  const workspaceId = String(currentWorkspace?.id || '').trim();

  const loadTasks = async () => {
    if (!workspaceId) {
      setTasks([]);
      return;
    }

    setLoading(true);
    setError(null);
    try {
      const allTasks = await storage.listTasks(workspaceId, { limit: 200 });
      const filteredTasks = (Array.isArray(allTasks) ? allTasks : []).filter((task) => !isInspectionTask(task));
      const enriched = filteredTasks.map((task) => ({
        ...task,
        taskType: getTaskType(task),
      }));

      setTasks(enriched);
    } catch (loadError) {
      setError(loadError);
      setTasks([]);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadTasks().catch(() => {});
  }, [workspaceId, cases]);

  const filteredByTab = useMemo(() => {
    let list = Array.isArray(tasks) ? tasks : [];

    if (activeTab === 'manual') {
      list = list.filter((task) => (
        !getTaskRuleMeta(task).isAuto &&
        task.taskType !== 'administrative' &&
        task.source !== 'procedural' &&
        !String(task.title || '').includes('طلب إطلاع')
      ));
    } else if (activeTab === 'procedural') {
      list = list.filter((task) => (
        task.taskType === 'administrative' || task.source === 'procedural'
      ));
    } else if (activeTab === 'auto') {
      list = list.filter((task) => getTaskRuleMeta(task).isAuto);
    }

    if (activePriority !== 'all') {
      list = list.filter((t) => t.priority === activePriority);
    }

    if (searchQuery) {
      const q = searchQuery.toLowerCase();
      list = list.filter((t) =>
        [t.title, t.notes, String(t.caseId || '')].join(' ').toLowerCase().includes(q)
      );
    }

    return list;
  }, [tasks, activeTab, activePriority, searchQuery]);

  const sortedTasks = useMemo(() => {
    return [...filteredByTab].sort((a, b) => {
      if (a.pinned && !b.pinned) return -1;
      if (!a.pinned && b.pinned) return 1;

      const ca = classifyTask(a, cases, urgentDays);
      const cb = classifyTask(b, cases, urgentDays);

      if (ca.isOverdue && !cb.isOverdue) return -1;
      if (!ca.isOverdue && cb.isOverdue) return 1;

      if (ca.isUrgent && !cb.isUrgent) return -1;
      if (!ca.isUrgent && cb.isUrgent) return 1;

      if (ca.isImportant && !cb.isImportant) return -1;
      if (!ca.isImportant && cb.isImportant) return 1;

      if (a.dueDate && b.dueDate) return a.dueDate.localeCompare(b.dueDate);
      if (a.dueDate) return -1;
      if (b.dueDate) return 1;

      return 0;
    });
  }, [filteredByTab, cases, urgentDays]);

  const stats = useMemo(() => {
    const today = new Date().toISOString().split('T')[0];
    const openTasks = tasks.filter((t) => t.status !== 'done');

    return [
      {
        label: 'عاجلة',
        value: openTasks.filter((t) => {
          const d = t.dueDate ? Math.ceil((new Date(t.dueDate) - new Date()) / 86400000) : null;
          return d !== null && d >= 0 && d <= urgentDays;
        }).length,
        color: '#dc2626',
        bg: '#fee2e2',
        icon: '⚠️',
      },
      {
        label: 'متأخرة',
        value: openTasks.filter((t) => t.dueDate && t.dueDate < today).length,
        color: '#ea580c',
        bg: '#ffedd5',
        icon: '🔴',
      },
      {
        label: 'اليوم',
        value: openTasks.filter((t) => t.dueDate === today).length,
        color: '#d97706',
        bg: '#fef3c7',
        icon: '⚡',
      },
      {
        label: 'مثبتة',
        value: tasks.filter((t) => t.pinned).length,
        color: '#7c3aed',
        bg: '#ede9fe',
        icon: '📌',
      },
      {
        label: 'مكتملة',
        value: tasks.filter((t) => t.status === 'done').length,
        color: '#16a34a',
        bg: '#dcfce7',
        icon: '✅',
      },
    ];
  }, [tasks, urgentDays]);

  const handleCreateTask = async (event) => {
    event.preventDefault();
    if (!workspaceId) return;

    const title = String(newTask.title || '').trim();
    if (!title) return;

    await storage.createTask(workspaceId, {
      title,
      caseId: String(newTask.caseId || '').trim(),
      priority: String(newTask.priority || 'high'),
      dueDate: String(newTask.dueDate || '').trim(),
      notes: String(newTask.notes || '').trim(),
      reminderBefore: Number(newTask.reminderBefore || 0),
      taskType: String(newTask.taskType || 'manual'),
      assignedTo: String(newTask.assignedTo || '').trim(),
      status: 'open',
      autoGenerated: false,
      source: 'manual',
      pinned: false,
      createdAt: new Date().toISOString(),
    });

    setNewTask({
      title: '',
      caseId: '',
      priority: 'high',
      dueDate: '',
      notes: '',
      reminderBefore: 0,
      taskType: 'manual',
      assignedTo: '',
    });
    setShowAddForm(false);
    await loadTasks();
  };

  const handleToggleDone = async (task) => {
    if (!workspaceId || !task?.id) return;

    const newStatus = task.status === 'done' ? 'open' : 'done';

    await storage.updateTask(workspaceId, task.id, {
      status: newStatus,
      completedAt: newStatus === 'done' ? new Date().toISOString() : null,
    });

    setTasks((prev) => prev.map((t) => (
      t.id === task.id ? { ...t, status: newStatus } : t
    )));
  };

  const handleTogglePin = async (task) => {
    if (!workspaceId || !task?.id) return;

    await storage.updateTask(workspaceId, task.id, {
      pinned: !task.pinned,
    });

    setTasks((prev) =>
      prev.map((t) => (t.id === task.id ? { ...t, pinned: !t.pinned } : t))
    );
  };

  const manualTasks = useMemo(() => (
    filteredByTab.filter((task) => (
      !getTaskRuleMeta(task).isAuto &&
      task.taskType !== 'administrative' &&
      task.source !== 'procedural' &&
      !String(task.title || '').includes('طلب إطلاع')
    ))
  ), [filteredByTab]);

  const proceduralTasks = useMemo(() => (
    filteredByTab.filter((task) => task.taskType === 'administrative' || task.source === 'procedural')
  ), [filteredByTab]);

  const autoTasks = useMemo(() => (
    [...filteredByTab.filter((task) => getTaskRuleMeta(task).isAuto)]
      .sort((a, b) => String(b.createdAt || '').localeCompare(String(a.createdAt || '')))
  ), [filteredByTab]);

  if (!workspaceId) {
    return <div className="empty-state">لا يوجد workspace محدد</div>;
  }

  if (loading) {
    return <div className="loading-text">جاري تحميل المهام...</div>;
  }

  if (error) {
    return <div className="empty-state" style={{ color: '#b91c1c' }}>حدث خطأ أثناء تحميل المهام</div>;
  }

  const renderTaskCard = (task, compact = false) => {
    const { isUrgent, isImportant, isOverdue, daysLeft, relatedCase } = classifyTask(task, cases, urgentDays);
    const ruleMeta = getTaskRuleMeta(task);
    const autoSourceTitle = (() => {
      if (!ruleMeta.isAuto) return '';
      if (ruleMeta.ruleDisplayName && ruleMeta.ruleId) {
        return `${ruleMeta.ruleDisplayName} (${ruleMeta.ruleId})`;
      }
      if (ruleMeta.ruleDisplayName) return ruleMeta.ruleDisplayName;
      if (ruleMeta.ruleId) return ruleMeta.ruleId;
      return 'مهمة منشأة تلقائيًا بواسطة قاعدة';
    })();

    if (task.taskType === 'administrative') {
      return (
        <div
          key={task.id}
          style={{
            borderRight: '3px solid #0284c7',
            background: '#f0f9ff',
            border: '1px solid #bae6fd',
            borderRadius: 'var(--radius-sm)',
            padding: '10px 14px',
            marginBottom: 6,
          }}
        >
          <div style={{ display: 'flex', justifyContent: 'space-between', gap: 8 }}>
            <span style={{ fontSize: 14, fontWeight: 600 }}>📋 {task.title}</span>
            <span style={{ fontSize: 11, background: '#dbeafe', color: '#2563eb', padding: '1px 8px', borderRadius: 10 }}>
              إجراء إداري
            </span>
          </div>
          {task.assignedTo && (
            <div style={{ fontSize: 12, color: '#0284c7', marginTop: 4 }}>
              👤 {task.assignedTo}
            </div>
          )}
          {task.dueDate && (
            <div style={{ fontSize: 11, color: 'var(--text-muted)', marginTop: 2 }}>
              📅 {formatDate(task.dueDate)}
            </div>
          )}
          {task.caseId && relatedCase && (
            <div
              onClick={() => openCasePanel(task.caseId)}
              style={{ fontSize: 12, color: 'var(--primary)', cursor: 'pointer', marginTop: 2 }}
            >
              📁 {formatCaseNumber(relatedCase.caseNumber, relatedCase.caseYear, { displayOrder: displaySettings.caseNumberDisplayOrder })}
            </div>
          )}
        </div>
      );
    }

    const cardStyle = (() => {
      if (isOverdue) return {
        borderRight: '3px solid #dc2626',
        background: '#fff5f5',
      };
      if (isUrgent) return {
        borderRight: '3px solid #ea580c',
        background: '#fffbeb',
      };
      if (isImportant) return {
        borderRight: '3px solid #d97706',
        background: 'white',
      };
      if (task.pinned) return {
        borderRight: '3px solid #7c3aed',
        background: '#faf5ff',
      };
      return { borderRight: '3px solid var(--border)', background: 'white' };
    })();

    return (
      <div
        key={task.id}
        style={{
          ...cardStyle,
          border: '1px solid var(--border)',
          borderRadius: 'var(--radius-sm)',
          padding: compact ? '8px 10px' : '10px 14px',
          marginBottom: 6,
          opacity: task.status === 'done' ? 0.55 : 1,
          transition: 'all 0.15s',
        }}
      >
        <div style={{ display: 'flex', alignItems: 'flex-start', gap: 10 }}>
          <input
            type="checkbox"
            checked={task.status === 'done'}
            onChange={() => handleToggleDone(task)}
            style={{ marginTop: 3, cursor: 'pointer', width: 16, height: 16 }}
          />

          <div style={{ flex: 1, minWidth: 0 }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', gap: 8 }}>
              <span
                style={{
                  fontSize: compact ? 13 : 14,
                  fontWeight: isImportant || isUrgent ? 700 : 600,
                  textDecoration: task.status === 'done' ? 'line-through' : 'none',
                  color: task.status === 'done' ? 'var(--text-muted)' : 'var(--text-primary)',
                }}
              >
                {ruleMeta.isAuto && (
                  <span title={autoSourceTitle} style={{ marginLeft: 4, cursor: 'help' }}>
                    ⚙️
                  </span>
                )}
                {task.title}
              </span>

              <div style={{ display: 'flex', gap: 4, alignItems: 'center', flexShrink: 0 }}>
                {isOverdue && (
                  <span
                    style={{
                      fontSize: 10,
                      background: '#fee2e2',
                      color: '#dc2626',
                      padding: '1px 6px',
                      borderRadius: 10,
                      fontWeight: 700,
                    }}
                  >
                    متأخرة {Math.abs(daysLeft)} يوم
                  </span>
                )}
                {isUrgent && !isOverdue && (
                  <span
                    style={{
                      fontSize: 10,
                      background: '#ffedd5',
                      color: '#ea580c',
                      padding: '1px 6px',
                      borderRadius: 10,
                      fontWeight: 700,
                    }}
                  >
                    ⚠️ {daysLeft} يوم
                  </span>
                )}
                {isImportant && !isUrgent && !isOverdue && (
                  <span
                    style={{
                      fontSize: 10,
                      background: '#fef3c7',
                      color: '#d97706',
                      padding: '1px 6px',
                      borderRadius: 10,
                    }}
                  >
                    ⭐ مهمة
                  </span>
                )}

                <button
                  onClick={(e) => {
                    e.stopPropagation();
                    setEditingTask({ ...task });
                  }}
                  style={{
                    background: 'none',
                    border: 'none',
                    cursor: 'pointer',
                    color: 'var(--text-muted)',
                    fontSize: 13,
                    padding: '2px 6px',
                  }}
                  title="تعديل"
                >
                  ✏️
                </button>

                <button
                  onClick={() => handleTogglePin(task)}
                  title={task.pinned ? 'إلغاء التثبيت' : 'تثبيت'}
                  style={{
                    background: 'none',
                    border: 'none',
                    cursor: 'pointer',
                    fontSize: 14,
                    padding: 2,
                    color: task.pinned ? '#7c3aed' : '#cbd5e1',
                    transition: 'all 0.15s',
                  }}
                >
                  📌
                </button>
              </div>
            </div>

            <div style={{ display: 'flex', gap: 12, marginTop: 4, flexWrap: 'wrap', fontSize: 12 }}>
              {relatedCase && (
                <span
                  onClick={() => task.caseId && openCasePanel(task.caseId)}
                  style={{ color: 'var(--primary)', cursor: 'pointer' }}
                >
                  📁 {formatCaseNumber(relatedCase.caseNumber, relatedCase.caseYear, { displayOrder: displaySettings.caseNumberDisplayOrder })}
                  {relatedCase.flags?.isPlaintiff && ' ⚖️'}
                  {relatedCase.flags?.isImportant && ' ⭐'}
                </span>
              )}
              {task.dueDate && (
                <span
                  style={{
                    color: isOverdue ? '#dc2626' : isUrgent ? '#ea580c' : 'var(--text-muted)',
                    fontWeight: isOverdue ? 700 : 400,
                  }}
                >
                  📅 {formatDate(task.dueDate)}
                </span>
              )}
              {ruleMeta.isAuto && (
                <span
                  title={autoSourceTitle}
                  style={{
                    color: '#7c3aed',
                    background: '#f3e8ff',
                    borderRadius: 10,
                    padding: '1px 8px',
                    fontSize: 10,
                    fontWeight: 700,
                    cursor: 'help',
                  }}
                >
                  مهمة آلية
                </span>
              )}
              {task.notes && !compact && (
                <span style={{ color: 'var(--text-secondary)' }}>
                  {task.notes.length > 40 ? task.notes.substring(0, 40) + '...' : task.notes}
                </span>
              )}
            </div>
          </div>
        </div>
      </div>
    );
  };

  return (
    <div>
      <div className="page-header">
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <h1 className="page-title">المهام</h1>
          <span style={{ color: 'var(--text-muted)', fontSize: 13 }}>
            {tasks.filter((t) => t.status === 'open' && t.taskType !== 'auto').length} مفتوحة
          </span>
        </div>

        <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
          <input
            className="form-input"
            placeholder="بحث..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            style={{ width: 180, fontSize: 13 }}
          />

          <button
            className="btn-secondary"
            style={{ fontSize: 12, padding: '6px 10px' }}
            onClick={() => loadTasks()}
          >
            🔄 تحديث
          </button>

          <button
            type="button"
            className="btn-primary"
            onClick={() => setShowAddForm((s) => !s)}
            style={{ fontSize: 13 }}
          >
            + مهمة جديدة
          </button>
        </div>
      </div>

      <div
        style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(5, 1fr)',
          gap: 8,
          marginBottom: 16,
        }}
      >
        {stats.map((s) => (
          <div
            key={s.label}
            style={{
              background: s.value > 0 ? s.bg : 'var(--bg-page)',
              border: '1px solid',
              borderColor: s.value > 0 ? s.color + '40' : 'var(--border)',
              borderRadius: 'var(--radius-md)',
              padding: '10px 8px',
              textAlign: 'center',
              cursor: s.value > 0 ? 'pointer' : 'default',
              transition: 'all 0.15s',
            }}
          >
            <div style={{ fontSize: 14 }}>{s.icon}</div>
            <div
              style={{
                fontSize: 22,
                fontWeight: 800,
                color: s.value > 0 ? s.color : 'var(--text-muted)',
              }}
            >
              {s.value}
            </div>
            <div style={{ fontSize: 11, color: 'var(--text-secondary)' }}>{s.label}</div>
          </div>
        ))}
      </div>

      <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', marginBottom: 12 }}>
        {TABS.map((tab) => (
          <button
            key={tab.id}
            type="button"
            className={activeTab === tab.id ? 'btn-primary' : 'btn-secondary'}
            onClick={() => setActiveTab(tab.id)}
            title={tab.desc}
            style={{ fontSize: 13, padding: '6px 12px' }}
          >
            {tab.label}
          </button>
        ))}
      </div>

      {showAddForm && (
        <div className="card" style={{ marginBottom: 16 }}>
          <h3 style={{ margin: '0 0 12px', fontSize: 15 }}>+ مهمة جديدة</h3>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10 }}>
            <div className="form-group" style={{ gridColumn: '1 / -1' }}>
              <label className="form-label">نوع المهمة</label>
              <div style={{ display: 'flex', gap: 8 }}>
                {[
                  { value: 'manual', label: '⚡ مهمة عاجلة' },
                  { value: 'administrative', label: '📋 إجراء إداري' },
                ].map((type) => (
                  <button
                    key={type.value}
                    type="button"
                    className={newTask.taskType === type.value ? 'btn-primary' : 'btn-secondary'}
                    style={{ flex: 1, fontSize: 13 }}
                    onClick={() => setNewTask((t) => ({ ...t, taskType: type.value }))}
                  >
                    {type.label}
                  </button>
                ))}
              </div>
            </div>

            <div className="form-group" style={{ gridColumn: '1 / -1' }}>
              <label className="form-label">العنوان *</label>
              <input
                className="form-input"
                value={newTask.title}
                onChange={(e) => setNewTask((t) => ({ ...t, title: e.target.value }))}
                placeholder="عنوان المهمة..."
              />
            </div>

            <div className="form-group">
              <label className="form-label">القضية (اختياري)</label>
              <select
                className="form-input"
                value={newTask.caseId}
                onChange={(e) => setNewTask((t) => ({ ...t, caseId: e.target.value }))}
              >
                <option value="">بدون قضية — مهمة عامة</option>
                {(Array.isArray(cases) ? cases : []).map((c) => {
                  const num = formatCaseNumber(c.caseNumber, c.caseYear, { displayOrder: displaySettings.caseNumberDisplayOrder });
                  return (
                    <option key={c.id} value={c.id}>
                      {num} — {c.plaintiffName || ''}
                    </option>
                  );
                })}
              </select>
            </div>

            <div className="form-group">
              <label className="form-label">الأولوية</label>
              <select
                className="form-input"
                value={newTask.priority}
                onChange={(e) => setNewTask((t) => ({ ...t, priority: e.target.value }))}
              >
                <option value="critical">⚠️ حرجة</option>
                <option value="high">🔴 عالية</option>
                <option value="medium">🟡 متوسطة</option>
                <option value="low">🔵 منخفضة</option>
              </select>
            </div>

            <div className="form-group">
              <label className="form-label">تاريخ الاستحقاق</label>
              <input
                type="date"
                className="form-input"
                value={newTask.dueDate}
                onChange={(e) => setNewTask((t) => ({ ...t, dueDate: e.target.value }))}
              />
            </div>

            <div className="form-group">
              <label className="form-label">التذكير قبل (أيام)</label>
              <input
                type="number"
                className="form-input"
                value={newTask.reminderBefore || ''}
                placeholder="مثال: 3"
                onChange={(e) => setNewTask((t) => ({ ...t, reminderBefore: Number(e.target.value) }))}
              />
            </div>

            {newTask.taskType === 'administrative' && (
              <div className="form-group" style={{ gridColumn: '1 / -1' }}>
                <label className="form-label">الموظف المختص</label>
                <input
                  className="form-input"
                  value={newTask.assignedTo}
                  onChange={(e) => setNewTask((t) => ({ ...t, assignedTo: e.target.value }))}
                  placeholder="اسم الموظف المسؤول عن هذا الإجراء..."
                />
              </div>
            )}

            <div className="form-group" style={{ gridColumn: '1 / -1' }}>
              <label className="form-label">ملاحظات</label>
              <textarea
                className="form-input"
                rows={2}
                value={newTask.notes}
                onChange={(e) => setNewTask((t) => ({ ...t, notes: e.target.value }))}
                placeholder="تفاصيل إضافية..."
              />
            </div>
          </div>

          <div style={{ display: 'flex', gap: 8, marginTop: 8 }}>
            <button type="button" className="btn-primary" onClick={handleCreateTask}>
              حفظ المهمة
            </button>
            <button
              type="button"
              className="btn-secondary"
              onClick={() => setShowAddForm(false)}
            >
              إلغاء
            </button>
          </div>
        </div>
      )}

      <div className="filter-chips" style={{ marginBottom: 16 }}>
        <button type="button" className={`filter-chip ${activePriority === 'all' ? 'active' : ''}`} onClick={() => setActivePriority('all')}>
          كل الأولويات
        </button>
        <button type="button" className={`filter-chip ${activePriority === 'critical' ? 'active' : ''}`} onClick={() => setActivePriority('critical')}>
          حرجة
        </button>
        <button type="button" className={`filter-chip ${activePriority === 'high' ? 'active' : ''}`} onClick={() => setActivePriority('high')}>
          عالية
        </button>
        <button type="button" className={`filter-chip ${activePriority === 'medium' ? 'active' : ''}`} onClick={() => setActivePriority('medium')}>
          متوسطة
        </button>
        <button type="button" className={`filter-chip ${activePriority === 'low' ? 'active' : ''}`} onClick={() => setActivePriority('low')}>
          منخفضة
        </button>
      </div>

      {(() => {
        const visibleTasks =
          activeTab === 'manual'
            ? manualTasks
            : activeTab === 'procedural'
              ? proceduralTasks
              : activeTab === 'auto'
                ? autoTasks
                : sortedTasks;

        return visibleTasks.length === 0 ? (
          <div className="empty-state">لا توجد مهام مطابقة</div>
        ) : (
          <>
            {visibleTasks.map((task) => renderTaskCard(task))}

            {(activeTab === 'auto' || activeTab === 'all') && (
              <details
                style={{
                  marginTop: 16,
                  cursor: 'pointer',
                }}
                open={activeTab === 'auto'}
              >
                <summary
                  style={{
                    padding: '8px 12px',
                    background: 'var(--bg-page)',
                    borderRadius: 'var(--radius-sm)',
                    fontSize: 13,
                    color: 'var(--text-secondary)',
                    userSelect: 'none',
                    fontWeight: 600,
                  }}
                >
                  ⚙️ المهام التلقائية ({autoTasks.length}) — طلبات الإطلاع والمواعيد
                </summary>
                <div style={{ marginTop: 8 }}>
                  {autoTasks.map((task) => renderTaskCard(task, true))}
                </div>
              </details>
            )}
          </>
        );
      })()}

      {editingTask && (
        <div
          style={{
            position: 'fixed',
            inset: 0,
            background: 'rgba(0,0,0,0.4)',
            zIndex: 500,
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
          }}
        >
          <div
            style={{
              background: 'white',
              borderRadius: 'var(--radius-lg)',
              padding: 24,
              width: 440,
              direction: 'rtl',
            }}
          >
            <h3 style={{ margin: '0 0 16px' }}>تعديل المهمة</h3>

            <div className="form-group">
              <label className="form-label">العنوان</label>
              <input
                className="form-input"
                value={editingTask.title || ''}
                onChange={(e) => setEditingTask((t) => ({ ...t, title: e.target.value }))}
              />
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10 }}>
              <div className="form-group">
                <label className="form-label">الأولوية</label>
                <select
                  className="form-input"
                  value={editingTask.priority || 'medium'}
                  onChange={(e) => setEditingTask((t) => ({ ...t, priority: e.target.value }))}
                >
                  <option value="critical">⚠️ حرجة</option>
                  <option value="high">🔴 عالية</option>
                  <option value="medium">🟡 متوسطة</option>
                  <option value="low">🔵 منخفضة</option>
                </select>
              </div>

              <div className="form-group">
                <label className="form-label">تاريخ الاستحقاق</label>
                <input
                  type="date"
                  className="form-input"
                  value={editingTask.dueDate || ''}
                  onChange={(e) => setEditingTask((t) => ({ ...t, dueDate: e.target.value }))}
                />
              </div>
            </div>

            <div className="form-group">
              <label className="form-label">ملاحظات</label>
              <textarea
                className="form-input"
                rows={2}
                value={editingTask.notes || ''}
                onChange={(e) => setEditingTask((t) => ({ ...t, notes: e.target.value }))}
              />
            </div>

            <div style={{ display: 'flex', gap: 8, marginTop: 8 }}>
              <button
                className="btn-primary"
                style={{ flex: 1 }}
                onClick={async () => {
                  await storage.updateTask(workspaceId, editingTask.id, {
                    title: editingTask.title,
                    priority: editingTask.priority,
                    dueDate: editingTask.dueDate,
                    notes: editingTask.notes,
                  });

                  setTasks((prev) => prev.map((t) => (
                    t.id === editingTask.id
                      ? {
                        ...t,
                        title: editingTask.title,
                        priority: editingTask.priority,
                        dueDate: editingTask.dueDate,
                        notes: editingTask.notes,
                      }
                      : t
                  )));

                  setEditingTask(null);
                }}
              >
                حفظ
              </button>

              <button className="btn-secondary" onClick={() => setEditingTask(null)}>
                إلغاء
              </button>

              <button
                onClick={async () => {
                  const proceed = await confirmDialog('حذف هذه المهمة؟', {
                    title: 'تأكيد الحذف',
                    confirmLabel: 'حذف',
                    cancelLabel: 'إلغاء',
                    danger: true,
                  });
                  if (!proceed) return;
                  await storage.deleteTask(workspaceId, editingTask.id);
                  setTasks((prev) => prev.filter((t) => t.id !== editingTask.id));
                  setEditingTask(null);
                }}
                style={{
                  background: '#fee2e2',
                  border: 'none',
                  borderRadius: 'var(--radius-sm)',
                  padding: '8px 14px',
                  cursor: 'pointer',
                  color: '#dc2626',
                  fontFamily: 'Cairo',
                  fontSize: 13,
                }}
              >
                حذف
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
